### ISSUE TITLE
bundling mini-apps cause crashes

### ISSUE THREAD

**Issue by keithlimmontajes** [callstack/repack#619]
## Environment

MAC i7 Core Intel
Xcode 15
Android Studio

"react-native": "0.72.11",
"@callstack/repack": "3.7.0",
"node: 18.2"

## Description

I have a react native app, using callstack, based on the https://github.com/callstack/super-app-showcase/tree/main, We created a Host-app and a mini-app, now the issue is, my Mini-app is taking too long to bundling locally even the deployed server, there is crashing after a minute when the bundling is 32% on the mini-app...

is there's a way to extend the timeout for bundling the mini-app or missconfig on my end here attached the files and errors encounter:

<img width="418" alt="image" src="https://github.com/callstack/repack/assets/46596249/443f2fff-2b77-4e20-be93-4242ec646094">

host-app -> index.js
[host-app.webpack.config.mjs.zip](https://github.com/callstack/repack/files/15289074/host-app.webpack.config.mjs.zip)
[package.json.zip](https://github.com/callstack/repack/files/15289075/package.json.zip)
<img width="950" alt="Screenshot 2024-05-13 at 11 30 40 AM" src="https://github.com/callstack/repack/assets/46596249/0b6b00e8-0e66-47af-b2ef-4b90016dd231">
[webpack.config.mjs.zip](https://github.com/callstack/repack/files/15289076/webpack.config.mjs.zip)

// Define containers URL
let containers = {
  Landers: `${CONFIG.LANDERS_CONTAINER_URL}/[name][ext]`,
};

// Create URL resolver
let resolveURL = Federated.createURLResolver({
  containers,
});

// Add resolver to ScriptManager
ScriptManager.shared.addResolver(async (scriptId, caller) => {
  try {
    // Implement timeout logic here
    const timeoutDuration = 120000; // 2 minutes in milliseconds

    // Use Promise.race to race between fetch and timeout
    const scriptPromise = fetchScript(scriptId, caller);
    const timeoutPromise = new Promise((resolve, reject) => {
      setTimeout(() => {
        reject(new Error('Script loading timed out'));
      }, timeoutDuration);
    });

    // Wait for either the script fetch or timeout
    const script = await Promise.race([scriptPromise, timeoutPromise]);

    // Return the script
    return script;
  } catch (error) {
    console.error('Error loading script:', error);
    return undefined;
  }
});

// Helper function to fetch script with retries
async function fetchScript(scriptId, caller) {
  // Your existing script fetching logic goes here
  let url;

  if (caller === 'main') {
    url = Script.getDevServerURL(scriptId);
  } else {
    url = resolveURL(scriptId, caller);
  }

  if (!url) return undefined;

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load script: ${response.status} ${response.statusText}`,
    );
  }

  console.log('====================== !!!!!!', url);
  if (Platform.OS === 'android') {
    if (scriptId === 'Landers') {
      url = `${url}?platform=${Platform.OS}`;
    }
  }

  const scriptContent = await response.text();
  return {
    url,
    content: scriptContent,
  };
}

// Register the app component
AppRegistry.registerComponent(appName, () => App);

## Reproducible Demo

host yarn "start": "react-native webpack-start --resetCache"
mini-app yarn  "start": "react-native webpack-start --port 9001 --resetCache",

**Comment by jbroma** [comment]
Hi @keithlimmontajes, 

please try upgrading to `@callstack/repakck@4.0.0` first and seeing if that helps, we fixed a lot of issues there!

can you show some logs where the error occurs? The logs you've provided just show the bundling progress.

**Comment by keithlimmontajes** [comment]
Hi @jbroma i upgraded to 4.0.0 still having the bundling crash, i dont received any errors, on the mini-app console, heres the completed logs..

yarn start:landers
ℹ [15:23:49.435Z][DevServer] Server listening at http://[::1]:9001 
ℹ [15:23:49.437Z][DevServer] Server listening at http://127.0.0.1:9001 
⇢ [15:25:09.332Z][LoggerPlugin] Compiling android: 3% setup (watch run) 
ℹ [15:25:09.385Z][DevServer] Successfully run: /Users/snapmart/Library/Android/sdk/platform-tools/adb reverse tcp:9001 tcp:9001 
⇢ [15:25:11.183Z][LoggerPlugin] Compiling android: 26% building (3/10 entries 20/20 dependencies 3/19 modules) 
⇢ [15:25:12.993Z][LoggerPlugin] Compiling android: 26% building (3/10 entries 390/441 dependencies 16/200 modules) 
⇢ [15:25:14.989Z][LoggerPlugin] Compiling android: 26% building (3/10 entries 1113/1176 dependencies 66/438 modules) 
⇢ [15:25:17.023Z][LoggerPlugin] Compiling android: 26% building (3/10 entries 1819/1900 dependencies 146/686 modules) 
⇢ [15:25:19.781Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2439/2600 dependencies 234/907 modules) 
⇢ [15:25:21.773Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 3161/3300 dependencies 272/1007 modules) 
⇢ [15:25:23.360Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 3600/3674 dependencies 320/1065 modules) 
⇢ [15:25:25.878Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 4069/4156 dependencies 400/1189 modules) 
⇢ [15:25:27.174Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 4421/4500 dependencies 474/1306 modules) 
⇢ [15:25:29.814Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 5042/5205 dependencies 600/1413 modules) 
⇢ [15:25:32.790Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 5200/5340 dependencies 619/1445 modules) 
⇢ [15:25:34.354Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 5683/5800 dependencies 682/1528 modules) 
⇢ [15:25:36.082Z][LoggerPlugin] Compiling android: 31% building (4/10 entries 6050/6100 dependencies 790/1573 modules) 
⇢ [15:25:38.506Z][LoggerPlugin] Compiling android: 31% building (4/10 entries 7447/7500 dependencies 1167/1919 modules) 
⇢ [15:25:40.933Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 8142/8300 dependencies 1481/2000 modules) 
⇢ [15:25:43.290Z][LoggerPlugin] Compiling android: 53% building (8/10 entries 8901/8948 dependencies 1919/2172 modules) 
⇢ [15:25:45.129Z][LoggerPlugin] Compiling android: 59% building (9/10 entries 9457/9500 dependencies 2133/2313 modules) 
⇢ [15:25:46.307Z][LoggerPlugin] Compiling android: 59% building (9/10 entries 9600/9668 dependencies 2299/2338 modules) 
⇢ [15:25:48.299Z][LoggerPlugin] Compiling android: 59% building (9/10 entries 9870/9900 dependencies 2351/2431 modules) 
⇢ [15:25:50.427Z][LoggerPlugin] Compiling android: 62% building (52/54 entries 10194/10196 dependencies 2492/2494 modules) 
⇢ [15:25:50.427Z][LoggerPlugin] Compiling android: 63% building (53/54 entries 10195/10196 dependencies 2493/2494 modules) 
ℹ [15:25:55.043Z][LoggerPlugin] Bundle built with warnings { time: 45709 } 
⚠ [15:25:55.043Z][LoggerPlugin] Warning in "./node_modules/react-native-reanimated/src/reanimated2/jestUtils.ts": Critical dependency: require function is used in a way in which dependencies cannot be statically extracted 
⚠ [15:25:55.043Z][LoggerPlugin] Warning in "./node_modules/react-native-reanimated/src/reanimated2/js-reanimated/index.ts": Module not found: Error: Can't resolve 'react-native-web/dist/exports/StyleSheet/compiler/createReactDOMStyle' in '/Users/snapmart/Desktop/SUPER_APP/superapp/apps/landers-app/node_modules/react-native-reanimated/src/reanimated2/js-reanimated' 
⚠ [15:25:55.043Z][LoggerPlugin] Warning in "./node_modules/react-native-reanimated/src/reanimated2/js-reanimated/index.ts": Module not found: Error: Can't resolve 'react-native-web/dist/exports/StyleSheet/preprocess' in '/Users/snapmart/Desktop/SUPER_APP/superapp/apps/landers-app/node_modules/react-native-reanimated/src/reanimated2/js-reanimated' 
⇢ [15:25:55.442Z][LoggerPlugin] Compiling android: 100%

**Comment by keithlimmontajes** [comment]
for the host this is what i get.. 

 [15:25:01.577Z][DevServer] GET 200 /index.bundle?platform=android&dev=true&minify=false&app=com.landersph.mobile_dev&modulesOnly=false&runModule=true request completed { responseTime: 69268.266779989 } 
⇢ [15:25:00.868Z][LoggerPlugin] Compiling android: 100%  
ℹ [15:25:03.545Z][DevServer] React Native client connected { clientId: 'client#0' } 
ℹ [15:25:04.645Z][DevServer] HMR client connected { clientId: 'client#0', platform: 'android' } 
ℹ [15:25:08.297Z][Console] [HMRClient] Connecting... {"url": "ws://localhost:8081/__hmr?platform=android"} 
✖ [15:25:08.609Z][Console] Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter? 
ℹ [15:25:08.609Z][Console] 777.4545454545455 
ℹ [15:25:08.609Z][Console] Running "HostApp" with {"rootTag":11} 
ℹ [15:25:08.609Z][Console] showErrorModal false 
ℹ [15:25:08.609Z][Console] #### undefined undefined 
ℹ [15:25:08.610Z][Console] ######### token null 
ℹ [15:25:08.610Z][Console] ######### loadingLogo false 
ℹ [15:25:08.610Z][Console] ######### showLoginModal false 
ℹ [15:25:08.610Z][Console] ######### isLoadingAccount false 
ℹ [15:25:08.610Z][Console] ######### showWelcomeModal false 
ℹ [15:25:08.610Z][Console] Current Screen Route: HomeStack 
ℹ [15:25:08.610Z][Console] #### undefined undefined 
ℹ [15:25:08.610Z][Console] http://localhost:9001/Landers.container.bundle 
ℹ [15:25:08.610Z][Console] #### undefined undefined 
ℹ [15:25:08.610Z][Console] [HMRClient] Connected 
ℹ [15:25:08.611Z][Console] #### undefined undefined 
ℹ [15:25:08.611Z][Console] #### undefined undefined 
ℹ [15:25:08.896Z][DevServer] POST 200 /symbolicate request completed { responseTime: 578.3719609975815 } 
✖ [15:25:38.319Z][Console] [ScriptManager] Failed to load script: [NetworkFailure] {"cache": true, "caller": undefined, "locator": {"absolute": false, "body": undefined, "fetch": true, "headers": undefined, "method": "GET", "query": "platform=android", "timeout": 30000, "url": "http://localhost:9001/Landers.container.bundle", "verifyScriptSignature": "off"}, "scriptId": "Landers"} {"originalError": [Error: timeout]} 
✖ [15:25:38.799Z][Console] Error: Unhandled error. ([ScriptManager] Failed to load script:)

This error is located at:
    in Lazy (created by HomeScreen)
    in Suspense (created by HomeScreen)
    in RCTView (created by View)
    in View (created by HomeScreen)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by HomeScreen)
    in HomeScreen
    in Themed.HomeScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by HomeStacks)
    in HomeStacks
    in Themed.HomeStacks (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by DashboardNavigations)
    in DashboardNavigations (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by MainNavigator)
    in MainNavigator (created by RootNavigation)
    in RootNavigation (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in Provider (created by App)
    in ThemeProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in HostApp(RootComponent), js engine: hermes 
✖ [15:25:38.801Z][Console] Error: Unhandled error. ([ScriptManager] Failed to load script:)

This error is located at:
    in Lazy (created by HomeScreen)
    in Suspense (created by HomeScreen)
    in RCTView (created by View)
    in View (created by HomeScreen)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by HomeScreen)
    in HomeScreen
    in Themed.HomeScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by HomeStacks)
    in HomeStacks
    in Themed.HomeStacks (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by DashboardNavigations)
    in DashboardNavigations (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by MainNavigator)
    in MainNavigator (created by RootNavigation)
    in RootNavigation (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in Provider (created by App)
    in ThemeProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in HostApp(RootComponent), js engine: hermes 
ℹ [15:25:38.809Z][DevServer] POST 200 /symbolicate request completed { responseTime: 436.29993699491024 } 
ℹ [15:25:38.815Z][DevServer] POST 200 /symbolicate request completed { responseTime: 12.00220100581646 } 
ℹ [15:25:38.821Z][DevServer] POST 200 /symbolicate request completed { responseTime: 17.821956992149353 }

**Comment by keithlimmontajes** [comment]
@jbroma additional info, it only happens on 1st load, but when the mini-app is already bundle to 100% it will work, but the apk/ipa when you open it, it crash.. hope this info helps.. maybe its regarding to timeout on the bundling mini-app? and if ever do i need to extend it or how? this is how i render my mini-app



`const HomeBanners = React.lazy(() =>
  Federated.importModule('Landers', 'HomeBanners'),
);

  <React.Suspense
          fallback={
              <HomeBannerSkeleton />
          }>
          <HomeBanners />
  </React.Suspense>`

**Comment by jbroma** [comment]
@keithlimmontajes did you declare `reanimated` as a shared dependency? It should be declared as shared as it contains a native module.

**Comment by keithlimmontajes** [comment]
Yes, this is my host config

 new Repack.plugins.ModuleFederationPlugin({
        name: 'HostApp',
        shared: {
          react: {
            singleton: true,
            eager: true,
            requiredVersion: '18.2.0',
          },
          'react-native': {
            singleton: true,
            eager: true,
            requiredVersion: '0.72.11',
          },
          '@react-navigation/native': {
            singleton: true,
            eager: true,
            requiredVersion: '6.1.6',
          },
          '@react-navigation/native-stack': {
            singleton: true,
            eager: true,
            requiredVersion: '6.9.12',
          },
          'react-native-safe-area-context': {
            singleton: true,
            eager: true,
            requiredVersion: '^4.5.0',
          },
          'react-native-screens': {
            singleton: true,
            eager: true,
            requiredVersion: '3.20.0',
          },
          'react-native-reanimated': {
            singleton: true,
            eager: true,
            requiredVersion: '3.8.0',
          },
          'react-native-gesture-handler': {
            singleton: true,
            eager: true,
            requiredVersion: '2.15.0',
          },
          '@candlefinance/faster-image': {
            singleton: true,
            eager: true,
            requiredVersion: '1.3.3',
          },
          'react-native-svg': {
            singleton: true,
            eager: true,
            requiredVersion: '15.1.0',
          },
          '@shopify/flash-list': {
            singleton: true,
            eager: true,
            requiredVersion: '1.6.4',
          },
          'react-native-linear-gradient': {
            singleton: true,
            eager: true,
            requiredVersion: '2.8.3',
          },
          '@react-native-clipboard/clipboard': {
            singleton: true,
            eager: true,
            requiredVersion: '1.14.1',
          },
          'react-native-webview': {
            singleton: true,
            eager: true,
            requiredVersion: '13.8.6',
          },
          'react-native-fbsdk-next': {
            singleton: true,
            eager: true,
            requiredVersion: '12.1.4',
          },
          'react-native-fast-image': {
            singleton: true,
            eager: true,
            requiredVersion: '8.6.3',
          },
        },
        runtime: false,
      }),
    ],
  };
};

**Comment by jbroma** [comment]
It's also weird that it looks to load `react-native-web` modules, I would probably need a closer look at your setup to get to the bottom of this, but try adding `reanimated` to shared first

**Comment by keithlimmontajes** [comment]
yes, this is for the mini-app

 
 shared: {
          react: {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '18.2.0',
          },
          'react-native': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '0.72.11',
          },
          '@react-navigation/native': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '6.1.6',
          },
          '@react-navigation/stack': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '6.3.28',
          },

          '@react-navigation/native-stack': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '6.9.12',
          },
          'react-native-safe-area-context': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '4.9.0',
          },
          'react-native-screens': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '3.20.0',
          },
          'react-native-screens': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '3.20.0',
          },
          '@candlefinance/faster-image': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '1.3.3',
          },
          'react-native-fast-image': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '8.6.3',
          },
          '@react-native-clipboard/clipboard': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '1.13.2',
          },
          'react-native-size-matters': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '0.4.2',
          },
          'react-native-gesture-handler': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '2.15.0',
          },
          'react-native-reanimated-carousel': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '3.5.1',
          },
          'react-native-svg': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '15.0.0',
          },
          'react-native-reanimated': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '3.8.0',
          },
          '@shopify/flash-list': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '1.6.4',
          },
          'react-native-linear-gradient': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '2.8.3',
          },
          'react-native-fbsdk-next': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '13.0.0',
          },
          '@react-native-clipboard/clipboard': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '1.14.1',
          },
          'react-native-webview': {
            singleton: true,
            eager: STANDALONE,
            requiredVersion: '13.8.6',
          },
        },

**Comment by jbroma** [comment]
Could you please share a full repo with your setup? I'm afraid I won't be able to help without seeing the whole setup

**Comment by jbroma** [comment]
@keithlimmontajes Please try to create a minimal reproduction that's publicly available - I won't be able to help you with a private project - you can contact our sales team (jakub.stadniczuk@callstack.com) to inquire about such arrangements

**Comment by keithlimmontajes** [comment]
got it, ill make a  minimal reproduction  publicly available. Thanks ..

**Comment by jbroma** [comment]
note: this is unrelated to the issue above, and still needs a valid repro

**Comment by keithlimmontajes** [comment]
Hi @jbroma here's a public repo.. i tested it on android its working and have the same error encounter. Thanks..

https://github.com/keithlimmontajes/callstack-public

**Comment by keithlimmontajes** [comment]
Let me know if you still need more info.. Thanks thanks

**Comment by jbroma** [comment]
@keithlimmontajes I see the repro is quite large in size, could you please provide some steps to reproduce? Also by default the repo uses yarn PnP mode which def won't work with RN

**Comment by jbroma** [comment]
@keithlimmontajes any update on this?
